name: Build Cordova Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install project dependencies
        run: npm install

      - name: Add Android platform
        run: cordova platform add android

      - name: Build Android AAB
        run: cordova build android --release -- --packageType=bundle

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: platforms/android/app/build/outputs/bundle/release/*.aab

      - name: Build Android APK
        run: cordova build android --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: platforms/android/app/build/outputs/apk/release/*.apk
